/*
 * Synctera API
 *
 * <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>
 *
 * API version: 0.5.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera

import (
	"encoding/json"
	"time"
)

// BasePerson struct for BasePerson
type BasePerson struct {
	// Customer unique identifier
	Id *string `json:"id,omitempty"`
	// The date and time the resource was created.
	CreationTime *time.Time `json:"creation_time,omitempty"`
	// The date and time the resource was last updated.
	LastUpdatedTime *time.Time `json:"last_updated_time,omitempty"`
	// Customer's middle name
	MiddleName      *string   `json:"middle_name,omitempty"`
	LegalAddress    *Address1 `json:"legal_address,omitempty"`
	ShippingAddress *Address1 `json:"shipping_address,omitempty"`
	// Customer's full tax ID eg SSN formatted with hyphens. This optional parameter is required when running KYC on a customer. Input must match the pattern ^\\d{3}-\\d{2}-\\d{4}$. The response contains the last 4 digits only (e.g. 6789).
	Ssn *string `json:"ssn,omitempty"`
	// Customer's email
	Email *string `json:"email,omitempty"`
	// Customer's mobile phone number with country code in E.164 format
	PhoneNumber *string            `json:"phone_number,omitempty"`
	KycStatus   *CustomerKycStatus `json:"kyc_status,omitempty"`
	// Customer's KYC exemption
	KycExempt *bool `json:"kyc_exempt,omitempty"`
	// Date and time KYC was last run on the customer
	KycLastRun *time.Time `json:"kyc_last_run,omitempty"`
	// Customer's relationships with other accounts eg. guardian
	RelatedCustomers *[]Relationship1 `json:"related_customers,omitempty"`
	// User-supplied metadata. Do not use to store PII.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// NewBasePerson instantiates a new BasePerson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasePerson() *BasePerson {
	this := BasePerson{}
	return &this
}

// NewBasePersonWithDefaults instantiates a new BasePerson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasePersonWithDefaults() *BasePerson {
	this := BasePerson{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BasePerson) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BasePerson) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BasePerson) SetId(v string) {
	o.Id = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *BasePerson) GetCreationTime() time.Time {
	if o == nil || o.CreationTime == nil {
		var ret time.Time
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil || o.CreationTime == nil {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *BasePerson) HasCreationTime() bool {
	if o != nil && o.CreationTime != nil {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given time.Time and assigns it to the CreationTime field.
func (o *BasePerson) SetCreationTime(v time.Time) {
	o.CreationTime = &v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value if set, zero value otherwise.
func (o *BasePerson) GetLastUpdatedTime() time.Time {
	if o == nil || o.LastUpdatedTime == nil {
		var ret time.Time
		return ret
	}
	return *o.LastUpdatedTime
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil || o.LastUpdatedTime == nil {
		return nil, false
	}
	return o.LastUpdatedTime, true
}

// HasLastUpdatedTime returns a boolean if a field has been set.
func (o *BasePerson) HasLastUpdatedTime() bool {
	if o != nil && o.LastUpdatedTime != nil {
		return true
	}

	return false
}

// SetLastUpdatedTime gets a reference to the given time.Time and assigns it to the LastUpdatedTime field.
func (o *BasePerson) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime = &v
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise.
func (o *BasePerson) GetMiddleName() string {
	if o == nil || o.MiddleName == nil {
		var ret string
		return ret
	}
	return *o.MiddleName
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetMiddleNameOk() (*string, bool) {
	if o == nil || o.MiddleName == nil {
		return nil, false
	}
	return o.MiddleName, true
}

// HasMiddleName returns a boolean if a field has been set.
func (o *BasePerson) HasMiddleName() bool {
	if o != nil && o.MiddleName != nil {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given string and assigns it to the MiddleName field.
func (o *BasePerson) SetMiddleName(v string) {
	o.MiddleName = &v
}

// GetLegalAddress returns the LegalAddress field value if set, zero value otherwise.
func (o *BasePerson) GetLegalAddress() Address1 {
	if o == nil || o.LegalAddress == nil {
		var ret Address1
		return ret
	}
	return *o.LegalAddress
}

// GetLegalAddressOk returns a tuple with the LegalAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetLegalAddressOk() (*Address1, bool) {
	if o == nil || o.LegalAddress == nil {
		return nil, false
	}
	return o.LegalAddress, true
}

// HasLegalAddress returns a boolean if a field has been set.
func (o *BasePerson) HasLegalAddress() bool {
	if o != nil && o.LegalAddress != nil {
		return true
	}

	return false
}

// SetLegalAddress gets a reference to the given Address1 and assigns it to the LegalAddress field.
func (o *BasePerson) SetLegalAddress(v Address1) {
	o.LegalAddress = &v
}

// GetShippingAddress returns the ShippingAddress field value if set, zero value otherwise.
func (o *BasePerson) GetShippingAddress() Address1 {
	if o == nil || o.ShippingAddress == nil {
		var ret Address1
		return ret
	}
	return *o.ShippingAddress
}

// GetShippingAddressOk returns a tuple with the ShippingAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetShippingAddressOk() (*Address1, bool) {
	if o == nil || o.ShippingAddress == nil {
		return nil, false
	}
	return o.ShippingAddress, true
}

// HasShippingAddress returns a boolean if a field has been set.
func (o *BasePerson) HasShippingAddress() bool {
	if o != nil && o.ShippingAddress != nil {
		return true
	}

	return false
}

// SetShippingAddress gets a reference to the given Address1 and assigns it to the ShippingAddress field.
func (o *BasePerson) SetShippingAddress(v Address1) {
	o.ShippingAddress = &v
}

// GetSsn returns the Ssn field value if set, zero value otherwise.
func (o *BasePerson) GetSsn() string {
	if o == nil || o.Ssn == nil {
		var ret string
		return ret
	}
	return *o.Ssn
}

// GetSsnOk returns a tuple with the Ssn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetSsnOk() (*string, bool) {
	if o == nil || o.Ssn == nil {
		return nil, false
	}
	return o.Ssn, true
}

// HasSsn returns a boolean if a field has been set.
func (o *BasePerson) HasSsn() bool {
	if o != nil && o.Ssn != nil {
		return true
	}

	return false
}

// SetSsn gets a reference to the given string and assigns it to the Ssn field.
func (o *BasePerson) SetSsn(v string) {
	o.Ssn = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *BasePerson) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *BasePerson) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *BasePerson) SetEmail(v string) {
	o.Email = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *BasePerson) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *BasePerson) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *BasePerson) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetKycStatus returns the KycStatus field value if set, zero value otherwise.
func (o *BasePerson) GetKycStatus() CustomerKycStatus {
	if o == nil || o.KycStatus == nil {
		var ret CustomerKycStatus
		return ret
	}
	return *o.KycStatus
}

// GetKycStatusOk returns a tuple with the KycStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetKycStatusOk() (*CustomerKycStatus, bool) {
	if o == nil || o.KycStatus == nil {
		return nil, false
	}
	return o.KycStatus, true
}

// HasKycStatus returns a boolean if a field has been set.
func (o *BasePerson) HasKycStatus() bool {
	if o != nil && o.KycStatus != nil {
		return true
	}

	return false
}

// SetKycStatus gets a reference to the given CustomerKycStatus and assigns it to the KycStatus field.
func (o *BasePerson) SetKycStatus(v CustomerKycStatus) {
	o.KycStatus = &v
}

// GetKycExempt returns the KycExempt field value if set, zero value otherwise.
func (o *BasePerson) GetKycExempt() bool {
	if o == nil || o.KycExempt == nil {
		var ret bool
		return ret
	}
	return *o.KycExempt
}

// GetKycExemptOk returns a tuple with the KycExempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetKycExemptOk() (*bool, bool) {
	if o == nil || o.KycExempt == nil {
		return nil, false
	}
	return o.KycExempt, true
}

// HasKycExempt returns a boolean if a field has been set.
func (o *BasePerson) HasKycExempt() bool {
	if o != nil && o.KycExempt != nil {
		return true
	}

	return false
}

// SetKycExempt gets a reference to the given bool and assigns it to the KycExempt field.
func (o *BasePerson) SetKycExempt(v bool) {
	o.KycExempt = &v
}

// GetKycLastRun returns the KycLastRun field value if set, zero value otherwise.
func (o *BasePerson) GetKycLastRun() time.Time {
	if o == nil || o.KycLastRun == nil {
		var ret time.Time
		return ret
	}
	return *o.KycLastRun
}

// GetKycLastRunOk returns a tuple with the KycLastRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetKycLastRunOk() (*time.Time, bool) {
	if o == nil || o.KycLastRun == nil {
		return nil, false
	}
	return o.KycLastRun, true
}

// HasKycLastRun returns a boolean if a field has been set.
func (o *BasePerson) HasKycLastRun() bool {
	if o != nil && o.KycLastRun != nil {
		return true
	}

	return false
}

// SetKycLastRun gets a reference to the given time.Time and assigns it to the KycLastRun field.
func (o *BasePerson) SetKycLastRun(v time.Time) {
	o.KycLastRun = &v
}

// GetRelatedCustomers returns the RelatedCustomers field value if set, zero value otherwise.
func (o *BasePerson) GetRelatedCustomers() []Relationship1 {
	if o == nil || o.RelatedCustomers == nil {
		var ret []Relationship1
		return ret
	}
	return *o.RelatedCustomers
}

// GetRelatedCustomersOk returns a tuple with the RelatedCustomers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetRelatedCustomersOk() (*[]Relationship1, bool) {
	if o == nil || o.RelatedCustomers == nil {
		return nil, false
	}
	return o.RelatedCustomers, true
}

// HasRelatedCustomers returns a boolean if a field has been set.
func (o *BasePerson) HasRelatedCustomers() bool {
	if o != nil && o.RelatedCustomers != nil {
		return true
	}

	return false
}

// SetRelatedCustomers gets a reference to the given []Relationship1 and assigns it to the RelatedCustomers field.
func (o *BasePerson) SetRelatedCustomers(v []Relationship1) {
	o.RelatedCustomers = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *BasePerson) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasePerson) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *BasePerson) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *BasePerson) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

func (o BasePerson) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.CreationTime != nil {
		toSerialize["creation_time"] = o.CreationTime
	}
	if o.LastUpdatedTime != nil {
		toSerialize["last_updated_time"] = o.LastUpdatedTime
	}
	if o.MiddleName != nil {
		toSerialize["middle_name"] = o.MiddleName
	}
	if o.LegalAddress != nil {
		toSerialize["legal_address"] = o.LegalAddress
	}
	if o.ShippingAddress != nil {
		toSerialize["shipping_address"] = o.ShippingAddress
	}
	if o.Ssn != nil {
		toSerialize["ssn"] = o.Ssn
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.PhoneNumber != nil {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if o.KycStatus != nil {
		toSerialize["kyc_status"] = o.KycStatus
	}
	if o.KycExempt != nil {
		toSerialize["kyc_exempt"] = o.KycExempt
	}
	if o.KycLastRun != nil {
		toSerialize["kyc_last_run"] = o.KycLastRun
	}
	if o.RelatedCustomers != nil {
		toSerialize["related_customers"] = o.RelatedCustomers
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableBasePerson struct {
	value *BasePerson
	isSet bool
}

func (v NullableBasePerson) Get() *BasePerson {
	return v.value
}

func (v *NullableBasePerson) Set(val *BasePerson) {
	v.value = val
	v.isSet = true
}

func (v NullableBasePerson) IsSet() bool {
	return v.isSet
}

func (v *NullableBasePerson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasePerson(val *BasePerson) *NullableBasePerson {
	return &NullableBasePerson{value: val, isSet: true}
}

func (v NullableBasePerson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasePerson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
