/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera

import (
	"encoding/json"
)

// PlaidAccountVerificationAllOf struct for PlaidAccountVerificationAllOf
type PlaidAccountVerificationAllOf struct {
	// The token provided from Plaid to access the accounts.
	AccessToken string `json:"access_token"`
}

// NewPlaidAccountVerificationAllOf instantiates a new PlaidAccountVerificationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaidAccountVerificationAllOf(accessToken string) *PlaidAccountVerificationAllOf {
	this := PlaidAccountVerificationAllOf{}
	this.AccessToken = accessToken
	return &this
}

// NewPlaidAccountVerificationAllOfWithDefaults instantiates a new PlaidAccountVerificationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaidAccountVerificationAllOfWithDefaults() *PlaidAccountVerificationAllOf {
	this := PlaidAccountVerificationAllOf{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *PlaidAccountVerificationAllOf) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *PlaidAccountVerificationAllOf) GetAccessTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *PlaidAccountVerificationAllOf) SetAccessToken(v string) {
	o.AccessToken = v
}

func (o PlaidAccountVerificationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["access_token"] = o.AccessToken
	}
	return json.Marshal(toSerialize)
}

type NullablePlaidAccountVerificationAllOf struct {
	value *PlaidAccountVerificationAllOf
	isSet bool
}

func (v NullablePlaidAccountVerificationAllOf) Get() *PlaidAccountVerificationAllOf {
	return v.value
}

func (v *NullablePlaidAccountVerificationAllOf) Set(val *PlaidAccountVerificationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaidAccountVerificationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaidAccountVerificationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaidAccountVerificationAllOf(val *PlaidAccountVerificationAllOf) *NullablePlaidAccountVerificationAllOf {
	return &NullablePlaidAccountVerificationAllOf{value: val, isSet: true}
}

func (v NullablePlaidAccountVerificationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaidAccountVerificationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


