/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>

API version: 0.20.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
	"time"
)

// ApplicationResponse struct for ApplicationResponse
type ApplicationResponse struct {
	// Details about the applicant. The exact schema is to be determined with your bank.
	ApplicationDetails map[string]interface{} `json:"application_details"`
	// Application creation timestamp in RFC3339 format
	CreationTime time.Time `json:"creation_time"`
	// Customer ID for the application
	CustomerId string `json:"customer_id"`
	// Generated ID for the application
	Id string `json:"id"`
	// Timestamp of the last application modification in RFC3339 format
	LastUpdatedTime time.Time         `json:"last_updated_time"`
	Status          ApplicationStatus `json:"status"`
	Type            ApplicationType1  `json:"type"`
}

// NewApplicationResponse instantiates a new ApplicationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationResponse(applicationDetails map[string]interface{}, creationTime time.Time, customerId string, id string, lastUpdatedTime time.Time, status ApplicationStatus, type_ ApplicationType1) *ApplicationResponse {
	this := ApplicationResponse{}
	this.ApplicationDetails = applicationDetails
	this.CreationTime = creationTime
	this.CustomerId = customerId
	this.Id = id
	this.LastUpdatedTime = lastUpdatedTime
	this.Status = status
	this.Type = type_
	return &this
}

// NewApplicationResponseWithDefaults instantiates a new ApplicationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationResponseWithDefaults() *ApplicationResponse {
	this := ApplicationResponse{}
	return &this
}

// GetApplicationDetails returns the ApplicationDetails field value
func (o *ApplicationResponse) GetApplicationDetails() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ApplicationDetails
}

// GetApplicationDetailsOk returns a tuple with the ApplicationDetails field value
// and a boolean to check if the value has been set.
func (o *ApplicationResponse) GetApplicationDetailsOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationDetails, true
}

// SetApplicationDetails sets field value
func (o *ApplicationResponse) SetApplicationDetails(v map[string]interface{}) {
	o.ApplicationDetails = v
}

// GetCreationTime returns the CreationTime field value
func (o *ApplicationResponse) GetCreationTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value
// and a boolean to check if the value has been set.
func (o *ApplicationResponse) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationTime, true
}

// SetCreationTime sets field value
func (o *ApplicationResponse) SetCreationTime(v time.Time) {
	o.CreationTime = v
}

// GetCustomerId returns the CustomerId field value
func (o *ApplicationResponse) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *ApplicationResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *ApplicationResponse) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetId returns the Id field value
func (o *ApplicationResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApplicationResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApplicationResponse) SetId(v string) {
	o.Id = v
}

// GetLastUpdatedTime returns the LastUpdatedTime field value
func (o *ApplicationResponse) GetLastUpdatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdatedTime
}

// GetLastUpdatedTimeOk returns a tuple with the LastUpdatedTime field value
// and a boolean to check if the value has been set.
func (o *ApplicationResponse) GetLastUpdatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdatedTime, true
}

// SetLastUpdatedTime sets field value
func (o *ApplicationResponse) SetLastUpdatedTime(v time.Time) {
	o.LastUpdatedTime = v
}

// GetStatus returns the Status field value
func (o *ApplicationResponse) GetStatus() ApplicationStatus {
	if o == nil {
		var ret ApplicationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApplicationResponse) GetStatusOk() (*ApplicationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApplicationResponse) SetStatus(v ApplicationStatus) {
	o.Status = v
}

// GetType returns the Type field value
func (o *ApplicationResponse) GetType() ApplicationType1 {
	if o == nil {
		var ret ApplicationType1
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApplicationResponse) GetTypeOk() (*ApplicationType1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApplicationResponse) SetType(v ApplicationType1) {
	o.Type = v
}

func (o ApplicationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["application_details"] = o.ApplicationDetails
	}
	if true {
		toSerialize["creation_time"] = o.CreationTime
	}
	if true {
		toSerialize["customer_id"] = o.CustomerId
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["last_updated_time"] = o.LastUpdatedTime
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationResponse struct {
	value *ApplicationResponse
	isSet bool
}

func (v NullableApplicationResponse) Get() *ApplicationResponse {
	return v.value
}

func (v *NullableApplicationResponse) Set(val *ApplicationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationResponse(val *ApplicationResponse) *NullableApplicationResponse {
	return &NullableApplicationResponse{value: val, isSet: true}
}

func (v NullableApplicationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
