/*
Synctera API

<h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 

API version: 0.19.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package synctera_client

import (
	"encoding/json"
)

// ExternalCardListResponseAllOf struct for ExternalCardListResponseAllOf
type ExternalCardListResponseAllOf struct {
	// Array of External Cards
	ExternalCards []ExternalCardResponse `json:"external_cards"`
}

// NewExternalCardListResponseAllOf instantiates a new ExternalCardListResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalCardListResponseAllOf(externalCards []ExternalCardResponse) *ExternalCardListResponseAllOf {
	this := ExternalCardListResponseAllOf{}
	this.ExternalCards = externalCards
	return &this
}

// NewExternalCardListResponseAllOfWithDefaults instantiates a new ExternalCardListResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalCardListResponseAllOfWithDefaults() *ExternalCardListResponseAllOf {
	this := ExternalCardListResponseAllOf{}
	return &this
}

// GetExternalCards returns the ExternalCards field value
func (o *ExternalCardListResponseAllOf) GetExternalCards() []ExternalCardResponse {
	if o == nil {
		var ret []ExternalCardResponse
		return ret
	}

	return o.ExternalCards
}

// GetExternalCardsOk returns a tuple with the ExternalCards field value
// and a boolean to check if the value has been set.
func (o *ExternalCardListResponseAllOf) GetExternalCardsOk() ([]ExternalCardResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalCards, true
}

// SetExternalCards sets field value
func (o *ExternalCardListResponseAllOf) SetExternalCards(v []ExternalCardResponse) {
	o.ExternalCards = v
}

func (o ExternalCardListResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["external_cards"] = o.ExternalCards
	}
	return json.Marshal(toSerialize)
}

type NullableExternalCardListResponseAllOf struct {
	value *ExternalCardListResponseAllOf
	isSet bool
}

func (v NullableExternalCardListResponseAllOf) Get() *ExternalCardListResponseAllOf {
	return v.value
}

func (v *NullableExternalCardListResponseAllOf) Set(val *ExternalCardListResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalCardListResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalCardListResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalCardListResponseAllOf(val *ExternalCardListResponseAllOf) *NullableExternalCardListResponseAllOf {
	return &NullableExternalCardListResponseAllOf{value: val, isSet: true}
}

func (v NullableExternalCardListResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalCardListResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


